apiVersion: apps/v1
kind: Deployment
metadata:
  name: velos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velos-api
  template:
    metadata:
      labels:
        app: velos-api
    spec:
      containers:
        - name: api
          image: wafaebm/velos-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: meteo-secret
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: velos-api
spec:
  type: NodePort
  selector:
    app: velos-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081
